<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Description>RmlUi integration and public C# API for Vintage Story.</Description>
    <PackageId>VSRmlUi</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="VintagestoryAPI" HintPath="$(GameDirectory)/VintagestoryAPI.dll" Private="false" />
    <Reference Include="SkiaSharp" HintPath="$(GameDirectory)/Lib/SkiaSharp.dll" Private="false" />
    <None Include="modinfo.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="assets/**/*" CopyToOutputDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="VSRmlUi.Tests" />
    <InternalsVisibleTo Include="VSDirector.RmlTests" />
  </ItemGroup>
</Project>
