<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.0.3</Version>
    <Authors>VSCN-Studio</Authors>
    <Copyright>Copyright (c) 2026 VSCN-Studio</Copyright>
    <GameDirectory Condition="'$(GameDirectory)' == ''">$(MSBuildThisFileDirectory)..\Vintagestory</GameDirectory>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
